// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type AvailabilityFilter struct {
	HoursPerWeekMin *int32    `json:"hoursPerWeekMin,omitempty"`
	DaysAvailable   []Weekday `json:"daysAvailable,omitempty"`
}

type AvailabilityInput struct {
	HoursPerWeek  int32     `json:"hoursPerWeek"`
	DaysAvailable []Weekday `json:"daysAvailable"`
	Timezone      string    `json:"timezone"`
}

type LocationInput struct {
	City    string `json:"city"`
	State   string `json:"state"`
	Country string `json:"country"`
	Remote  bool   `json:"remote"`
}

type Mutation struct {
}

type NonprofitInput struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Website     string          `json:"website"`
	Ein         string          `json:"ein"`
	Size        NonprofitSize   `json:"size"`
	Causes      []string        `json:"causes"`
	Location    *LocationInput  `json:"location"`
	Logo        *graphql.Upload `json:"logo,omitempty"`
}

type ProfileInput struct {
	FirstName *string         `json:"firstName,omitempty"`
	LastName  *string         `json:"lastName,omitempty"`
	Bio       *string         `json:"bio,omitempty"`
	LinkedIn  *string         `json:"linkedIn,omitempty"`
	Portfolio *string         `json:"portfolio,omitempty"`
	Avatar    *graphql.Upload `json:"avatar,omitempty"`
	Causes    []string        `json:"causes,omitempty"`
}

type ProjectInput struct {
	NonprofitID    string         `json:"nonprofitId"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	SkillsNeeded   []string       `json:"skillsNeeded"`
	TimeCommitment TimeCommitment `json:"timeCommitment"`
	Urgency        UrgencyLevel   `json:"urgency"`
	StartDate      *string        `json:"startDate,omitempty"`
	EndDate        *string        `json:"endDate,omitempty"`
}

type Query struct {
}

type SignupInput struct {
	Email     string   `json:"email"`
	Password  string   `json:"password"`
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Role      UserRole `json:"role"`
}

type Subscription struct {
}
